Areas/Admin/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Restauracja_u_Domino.DataAccess.Data;
using Restauracja_u_Domino.Models;

namespace Restauracja_u_Domino.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DishesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        public DishesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Admin/Dishes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dishes.Include(d => d.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Dishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // GET: Admin/Dishes/Create
        public IActionResult Create()
        {
            var list = new SelectList(_context.Categories, "Id", "CategoryName");
            if (list.Count() == 0)
            {
                return RedirectToAction("Index", "Categories", new { Area = "Admin" });
            }
            ViewData["CategoryId"] = list;
            return View();
        }

        // POST: Admin/Dishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Price,Name,Description,ImageUrl,CategoryId")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images/dishes");
                    var extension = Path.GetExtension(files[0].FileName);
                    await using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filesStreams);
                    }
                    dish.ImageUrl = @"/images/dishes/" + fileName + extension;
                }
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", dish.CategoryId);
            return View(dish);
        }

        // GET: Admin/Dishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes.FindAsync(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", dish.CategoryId);
            return View(dish);
        }

        // POST: Admin/Dishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Price,Name,Description,ImageUrl,CategoryId")] Dish dish)
        {
            if (id != dish.Id)
            {
                return NotFound();
            }


            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var dishFromDb = _context.Dishes.Find(id);
            if (dishFromDb != null)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images/dishes");
                    var extension = Path.GetExtension(files[0].FileName);

                    if (dishFromDb.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, dishFromDb.ImageUrl.TrimStart('/'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    dishFromDb.ImageUrl = @$"/images/dishes/{ fileName }{extension}";
                    dish.ImageUrl = dishFromDb.ImageUrl;
                }
                dishFromDb.Name = dish.Name;
                dishFromDb.Price = dish.Price;
                dishFromDb.Description = dish.Description;
                dishFromDb.CategoryId = dish.CategoryId;
                await _context.SaveChangesAsync();

            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", dish.CategoryId);
            return View(dish);
        }

        // GET: Admin/Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Admin/Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dish = await _context.Dishes.FindAsync(id);
            _context.Dishes.Remove(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
            return _context.Dishes.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restauracja_u_Domino.Models;
using Restauracja_u_Domino.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Restauracja_u_Domino.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };
                IdentityResult result = await _roleManager.CreateAsync(identityRole);
                if (result.Succeeded)
                {
                    return RedirectToAction("index");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };
            IList<ApplicationUser> users = await _userManager.GetUsersInRoleAsync(role.Name);

            foreach (var user in users)
            {
                model.Users.Add(user.UserName);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel editRole)
        {
            var role = await _roleManager.FindByIdAsync(editRole.Id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = editRole.RoleName;
            IdentityResult result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View(editRole);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }
            var model = new List<UserRoleViewModel>();
            foreach (var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }
                model.Add(userRoleViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                return NotFound();
            }

            foreach (var userRole in model)
            {
                var user = await _userManager.FindByIdAsync(userRole.UserId);
                IdentityResult result = null;
                if (userRole.IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!userRole.IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }
            }
            return RedirectToAction("EditRole", new { Id = roleId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }
            IdentityResult result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Restauracja_u_Domino.DataAccess.Repository.IRepository;
using Restauracja_u_Domino.Models;
using Restauracja_u_Domino.ViewModels;

namespace Restauracja_u_Domino.Controllers
{
    public class MenuController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MenuController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Recommended()
        {
            MenuViewModel menuViewModel = new MenuViewModel();
            var dishes = _unitOfWork.RecommendedDishes.GetAll(includeProperties:"Dish");
            if (dishes.Any())
            {
                menuViewModel.Dishes = dishes.Select(i => i.Dish).ToList();
            }
            return View(menuViewModel);
        }
        public IActionResult Index(int? categoryId)
        {
            MenuViewModel menuViewModel = new MenuViewModel();
            Category category;

            if (categoryId == null)
            {
                category = _unitOfWork.Category.GetFirstOrDefault();
            }
            else
            {
                category = _unitOfWork.Category.GetFirstOrDefault(i => i.Id == categoryId);
            }
            var categories = _unitOfWork.Category.GetAll();
            
            if (categories.Any())
            {
                menuViewModel.Categories = categories.ToList();
            }

            if(category != null)
            {
                menuViewModel.SelectedCategory = category;
                //Add dishes 
                var dishes = _unitOfWork.Dish.GetAll(includeProperties: "Category").Where(i => i.Category == category);
                if (dishes.Any())
                {
                    menuViewModel.Dishes = dishes.ToList();
                }
            }
           
            return View(menuViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Restauracja u Domino">
    <meta property="og:image" content="https://dominorestauracja.azurewebsites.net/wb.png">
    <meta property="og:description" content="Restauracja u Domino to miejsce z tradycjami gdzie każdy znajdzie coś dla siebie.">
    <meta name="description" content="Restauracja u Domino to miejsce z tradycjami gdzie każdy znajdzie coś dla siebie.">
    <noscript>
        <meta http-equiv="refresh" content="0;url=@Url.Action("NoJSSupport", "Home", new {area = ""})">
    </noscript>
    <title>@ViewData["Title"] - Restauracja u Domino</title>
    <!-- css -->
    <environment include="Development">
        <!-- Production -->
        <link rel="stylesheet" href="~/css/site.min.css"/>
    </environment>
    <environment exclude="Development">
        <!-- Development -->
        <link rel="stylesheet" href="~/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/dark.css"/>
        <link rel="stylesheet" href="~/css/toastr.css"/>
        <link rel="stylesheet" href="~/lib/font-awesome/dist/css/font-awesome.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    @RenderSection("Head", false)
</head>
<body>
<!-- loader -->
<div id="loader">
    <div class="loader--logo">
        <a asp-area="" asp-controller="Home" asp-action="Index">
            <img alt="Loader" src="~/logo-loader.svg"/>
        </a>
    </div>
</div>
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top border-bottom shadow box-shadow b-5">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
        <img alt="Logo" src="~/logo.svg"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="collapseNavigation"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <partial name="_NavPartial"/>
        </ul>
        <ul class="navbar-nav ml-auto flex-wrap flex-row">
            <partial name="_LoginPartial"/>
        </ul>
    </div>
</nav>
<!-- main -->
<main role="main" id="main" class="dev-padding dev-margin">
    @RenderBody()
</main>
<!-- footer -->
<footer class="footer bg-light border-top box-shadow b-5 py-3">
    <div class="container text-center">
        &copy; Restauracja u Domino 2020
    </div>
</footer>
<!-- js -->
<environment include="Development">
    <!-- Production -->
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <!-- Development -->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/flatpickr.js"></script>
    <script src="~/js/pl.js"></script>
    <script src="~/js/toastr.js"></script>
    <script src="~/lib/font-awesome/dist/js/font-awesome.js"></script>
    <script src="~/js/sweetalert2@9.js"></script>
    <script src="~/js/gsap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Restauracja_u_Domino.Utilities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
    <div class="dropdown-menu p-0" aria-labelledby="dropdownMenu">
        @Html.ActiveActionLink("Polecane", "Recommended", "Menu", new {area = ""}, new {@class = "dropdown-item"}, false)
        @Html.ActiveActionLink("Kategorie", "Index", "Menu", new {area = ""}, new {@class = "dropdown-item"}, false)
    </div>
</li>
@if (User.IsInRole("User") || User.IsInRole("Admin") || User.IsInRole("Employee"))
{
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Rezerwacje
        </a>
        <div class="dropdown-menu p-0" aria-labelledby="dropdownUser">
            @Html.ActiveActionLink("Zarezerwuj", "Index", "Reservation", new {area = "User"}, new {@class = "dropdown-item"}, false)
            @Html.ActiveActionLink("Twoje Rezerwacje", "UserReservations", "Reservation", new {area = "User"}, new {@class = "dropdown-item"}, false)
        </div>
    </li>
}
else
{
    @Html.ActiveActionLink("Zarezerwuj", "Index", "Reservation", new {area = "User"}, new {@class = "nav-link"}, true)
}
@if (User.IsInRole("Admin"))
{
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Panel Administracyjny
        </a>
        <div class="dropdown-menu p-0" aria-labelledby="dropdownAdmin">
            @Html.ActiveActionLink("Zarządzaj Rolami", "Index", "Role", new {area = "Admin"}, new {@class = "dropdown-item"}, false)
            @Html.ActiveActionLink("Zarządzaj Kategoriami", "Index", "Categories", new {area = "Admin"}, new {@class = "dropdown-item"}, false)
            @Html.ActiveActionLink("Zarządzaj Daniami", "Index", "Dishes", new {area = "Admin"}, new {@class = "dropdown-item"}, false)
            @Html.ActiveActionLink("Zarządzaj Polecanymi", "Index", "RecommendedDishes", new {area = "Admin"}, new {@class = "dropdown-item"}, false)
            @Html.ActiveActionLink("Zarządzaj Stolikami", "Index", "Tables", new {area = "Admin"}, new {@class = "dropdown-item"}, false)
        </div>
    </li>
} else if (User.IsInRole("Employee"))
{
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Panel Pracowniczy
        </a>
        <div class="dropdown-menu p-0" aria-labelledby="dropdownAdmin">
            @Html.ActiveActionLink("Podgląd rezerwacji", "Index", "AllReservation", new {area = "Employee"}, new {@class = "dropdown-item"}, false)
        </div>
    </li>
}