Areas/Employee/Controllers/AllReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restauracja_u_Domino.DataAccess.Data;
using Restauracja_u_Domino.Models;

namespace Restauracja_u_Domino.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize(Roles="Employee, Admin")]
    public class AllReservationController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AllReservationController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Reservation> reservations = _db.Reservations.Include(r => r.User).Include(r => r.Table).Where(r => r.StartDate > DateTime.Now).ToList(); 
            return View(reservations);
        }

        [HttpGet]
        public IActionResult GetContact(int id)
        {
            var reservation = _db.Reservations.Include(r => r.User).FirstOrDefault(i => i.Id == id);
            if(reservation == null)
            {
                return NotFound();
            }

            return Json(reservation.User);
        }
    }
}

Areas/Employee/Views/AllReservation/Index.cshtml
@model IEnumerable<Restauracja_u_Domino.Models.Reservation>

@{
    ViewData["Title"] = "Index";
}
@section Head{ 
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
} 
<h1>Pogląd rezerwacji</h1>

@foreach(var reservation in Model)
{
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">stolik nr. @reservation.Table.Id</h5>
            <h6 class="card-subtitle mb-2 text-muted">od: @reservation.StartDate.ToString("MM-dd hh:mm") do: @reservation.EndDate.ToString("MM-dd hh:mm") </h6>
            <p class="card-text">Dla: @reservation.User.Name @reservation.User.Surname </p>
            <p class="card-text">Komentarz: @reservation.Comment</p>
            <button onclick="showContact(@reservation.Id)" class="card-link btn btn-primary">Kontakt</button>
        </div>
    </div>
}

@section Scripts{ 

    <script>
        function showContact(Id) {
            $.ajax({
                type: "Get",
                url: '@Url.Action("GetContact", "AllReservation")',
                data: { id: Id },
                success: function (data) {
                    Swal.fire({
                        title: "Kontakt",
                        html: 'Imię: ' + data.name + '</br>' + "Nazwisko: " + data.surname + '</br>' + "Email: " + data.email + '</br>' + "Telefon: " + data.phoneNumber
                    });
                      
                }

            })
        }
    </script>
}